# Generated by Django 6.0.2 on 2026-03-06 20:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
