# Generated by Django 6.0.2 on 2026-03-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_postal_shippingaddress_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(blank=True, default='123 Street, New York, USA2'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=254),
        ),
    ]
